#!/bin/bash

OPT=$1

BASE_DIR=$(cd $(dirname $0); pwd)

mkdir -p $BASE_DIR/resources/tmp
(cd $BASE_DIR/resources/tmp; curl -O http://rpms.famillecollet.com/enterprise/remi-release-7.rpm)
mkdir -p $BASE_DIR/resources/keys
cp -p ~/cert/idp-proxy/nbhub.ecloud.nii.ac.jp.chained.cer $BASE_DIR/resources/keys/idp-proxy.chained.cer
cp -p ~/cert/idp-proxy/nbhub.ecloud.nii.ac.jp.cer $BASE_DIR/resources/keys/idp-proxy.cer
cp -p ~/cert/idp-proxy/nbhub.ecloud.nii.ac.jp.key $BASE_DIR/resources/keys/idp-proxy.key

sudo docker build $OPT -t idp-proxy:latest ./

