name: Build and push Docker image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | sed -e s,/,-,)" >> $GITHUB_OUTPUT
        id: extract_branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Build and push: idp-proxy"
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: "${{ secrets.DOCKERHUB_NAMESPACE }}/coursewarehub-idp-proxy:${{ steps.extract_branch.outputs.branch }}"
          build-args: |
            ATTRIBUTE_AGGREGATOR_URL=${{ vars.ATTRIBUTE_AGGREGATOR_URL || 'https://github.com/NII-cloud-operation/simplesamlphp-module-attributeaggregator' }}
            ATTRIBUTE_AGGREGATOR_BRANCH=${{ vars.ATTRIBUTE_AGGREGATOR_BRANCH || 'dev-2.x-gakunin-cloud-gateway' }}
